#!/bin/sh
ln -s ~/.vim/bundle/vim-one/bin/onevim ~/bin/mvime
ln -s ~/.vim/bundle/vim-one/bin/onevim ~/bin/mvims
ln -s ~/.vim/bundle/vim-one/bin/onevim ~/bin/mvimv
ln -s ~/.vim/bundle/vim-one/bin/onevim ~/bin/mvimt
